name: 04 Using Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: Printing Dir Structure
          run: ls
          

          